// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jM0beTaxzXNFNoSWHz-Oyr83gknsIIM',
    appId: '1:556817379074:web:015d5964dc7e331620dc1b',
    messagingSenderId: '556817379074',
    projectId: 'crudp2',
    authDomain: 'crudp2.firebaseapp.com',
    storageBucket: 'crudp2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8wTkxy3LaSFHyFkDDDAplqiKfaguk8g',
    appId: '1:556817379074:android:3c5c3c5f2391d1a820dc1b',
    messagingSenderId: '556817379074',
    projectId: 'crudp2',
    storageBucket: 'crudp2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtN1hUACIgqva6bBTn7jgFfZ5OzoK1rQ',
    appId: '1:556817379074:ios:10472a3529b3905920dc1b',
    messagingSenderId: '556817379074',
    projectId: 'crudp2',
    storageBucket: 'crudp2.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABtN1hUACIgqva6bBTn7jgFfZ5OzoK1rQ',
    appId: '1:556817379074:ios:10472a3529b3905920dc1b',
    messagingSenderId: '556817379074',
    projectId: 'crudp2',
    storageBucket: 'crudp2.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jM0beTaxzXNFNoSWHz-Oyr83gknsIIM',
    appId: '1:556817379074:web:fc82ac09d973e2b920dc1b',
    messagingSenderId: '556817379074',
    projectId: 'crudp2',
    authDomain: 'crudp2.firebaseapp.com',
    storageBucket: 'crudp2.appspot.com',
  );
}
