// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOW6K3He17pNU-2XS0Uit1Xv4ViNuftjA',
    appId: '1:789156060065:web:3ebc4e6413c50aa8ab89e0',
    messagingSenderId: '789156060065',
    projectId: 'crudcitas-52feb',
    authDomain: 'crudcitas-52feb.firebaseapp.com',
    storageBucket: 'crudcitas-52feb.appspot.com',
    measurementId: 'G-YXWR95RP7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8DvytoKLVMEWvTZRhbL2X54QZHc2cfU',
    appId: '1:789156060065:android:a0a87a41c9eca0a6ab89e0',
    messagingSenderId: '789156060065',
    projectId: 'crudcitas-52feb',
    storageBucket: 'crudcitas-52feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhcJwjTpw-N5xQ6eu-dgrvAZ96BWRjyw',
    appId: '1:789156060065:ios:170c91106e8516e9ab89e0',
    messagingSenderId: '789156060065',
    projectId: 'crudcitas-52feb',
    storageBucket: 'crudcitas-52feb.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuhcJwjTpw-N5xQ6eu-dgrvAZ96BWRjyw',
    appId: '1:789156060065:ios:170c91106e8516e9ab89e0',
    messagingSenderId: '789156060065',
    projectId: 'crudcitas-52feb',
    storageBucket: 'crudcitas-52feb.appspot.com',
    iosBundleId: 'com.example.prueba2',
  );
}
